#!/bin/sh
source /etc/os-release
distro_like=$ID_LIKE
sdir=$(pwd)

cd /etc/X11 && echo "cd -> /etc/X11"
# Installing packages using system package manager
case $ID in
    gentoo)
        packList="gentoo/$ID.txt"
        echo "Distro: Gentoo"
        echo "Package List: $packList"
        echo "Package Manager: emerge" && sleep 5
        echo "If you want to change the make.conf do it now to the one in the gentoo directory because the other one is going to be overwritten"
        echo "Pretending emerge, you have 1 minute to look over the packages before it will begin" && sleep 2
#        xargs emerge -pv < $packList && sleep 60 ; echo "Time's up, installing packages for your system from $packList with emerge, this will begin in 5 seconds" && sleep 5
 #       mv gentoo/make.conf /etc/portage/ ; mv gentoo/steam /etc/portage/package.use ; xargs emerge -v < $packList
        ;;
esac

if [ `xinput --list | grep TPPS/2 | awk {print'$3''$4''$5'}` = TPPS/2IBMTrackPoint ]; then
    echo "moving 25-thinkpad.conf to /etc/X11" && sleep 2
else
    echo "deleting 25-thinkpad.conf"
fi

echo "Making necessary directories if you dont already have them" && sleep 2
cd $sdir && echo "cd -> $sdir" && sleep 2
echo "autosetup script completed, use 'man dwm' for instructions on keyboard shortcuts and 'startx' to start a dwm session"
